# Generated by Django 5.2.11 on 2026-08-22 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_shipment_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Credit', 'Credit'), ('Cash on delivery', 'Cash on Delivery'), ('Online Payment', 'Online Payment')], max_length=20),
        ),
    ]
